-- Seed system exercises (run after migration)
-- Generated from exercise-seed.ts

insert into exercises (name, muscle_group, equipment_type, is_system) values
('Barbell Bench Press', 'chest', 'barbell', true),
('Incline Barbell Bench Press', 'chest', 'barbell', true),
('Decline Barbell Bench Press', 'chest', 'barbell', true),
('Dumbbell Bench Press', 'chest', 'dumbbell', true),
('Incline Dumbbell Press', 'chest', 'dumbbell', true),
('Dumbbell Fly', 'chest', 'dumbbell', true),
('Incline Dumbbell Fly', 'chest', 'dumbbell', true),
('Cable Crossover', 'chest', 'cable', true),
('Pec Deck Machine', 'chest', 'machine', true),
('Chest Press Machine', 'chest', 'machine', true),
('Push-Up', 'chest', 'bodyweight', true),
('Weighted Push-Up', 'chest', 'bodyweight', true),
('Dips', 'chest', 'bodyweight', true),
('Smith Machine Bench Press', 'chest', 'machine', true),
('Landmine Press', 'chest', 'barbell', true),
('Floor Press', 'chest', 'barbell', true),
('Deadlift', 'back', 'barbell', true),
('Romanian Deadlift', 'back', 'barbell', true),
('Sumo Deadlift', 'back', 'barbell', true),
('Pull-Up', 'back', 'bodyweight', true),
('Chin-Up', 'back', 'bodyweight', true),
('Lat Pulldown', 'back', 'cable', true),
('Wide Grip Lat Pulldown', 'back', 'cable', true),
('Close Grip Lat Pulldown', 'back', 'cable', true),
('Seated Cable Row', 'back', 'cable', true),
('Barbell Row', 'back', 'barbell', true),
('Pendlay Row', 'back', 'barbell', true),
('Dumbbell Row', 'back', 'dumbbell', true),
('Chest Supported Row', 'back', 'machine', true),
('T-Bar Row', 'back', 'barbell', true),
('Machine Row', 'back', 'machine', true),
('Straight Arm Pulldown', 'back', 'cable', true),
('Face Pull', 'back', 'cable', true),
('Rack Pull', 'back', 'barbell', true),
('Inverted Row', 'back', 'bodyweight', true),
('Back Squat', 'legs', 'barbell', true),
('Front Squat', 'legs', 'barbell', true),
('Goblet Squat', 'legs', 'dumbbell', true),
('Leg Press', 'legs', 'machine', true),
('Hack Squat', 'legs', 'machine', true),
('Leg Extension', 'legs', 'machine', true),
('Leg Curl', 'legs', 'machine', true),
('Lying Leg Curl', 'legs', 'machine', true),
('Seated Leg Curl', 'legs', 'machine', true),
('Bulgarian Split Squat', 'legs', 'dumbbell', true),
('Walking Lunge', 'legs', 'dumbbell', true),
('Reverse Lunge', 'legs', 'dumbbell', true),
('Step-Up', 'legs', 'dumbbell', true),
('Hip Thrust', 'legs', 'barbell', true),
('Glute Bridge', 'legs', 'bodyweight', true),
('Calf Raise', 'legs', 'machine', true),
('Standing Calf Raise', 'legs', 'machine', true),
('Seated Calf Raise', 'legs', 'machine', true),
('Overhead Press', 'shoulders', 'barbell', true),
('Military Press', 'shoulders', 'barbell', true),
('Dumbbell Shoulder Press', 'shoulders', 'dumbbell', true),
('Arnold Press', 'shoulders', 'dumbbell', true),
('Lateral Raise', 'shoulders', 'dumbbell', true),
('Cable Lateral Raise', 'shoulders', 'cable', true),
('Front Raise', 'shoulders', 'dumbbell', true),
('Rear Delt Fly', 'shoulders', 'dumbbell', true),
('Reverse Pec Deck', 'shoulders', 'machine', true),
('Upright Row', 'shoulders', 'barbell', true),
('Machine Shoulder Press', 'shoulders', 'machine', true),
('Barbell Curl', 'arms', 'barbell', true),
('EZ Bar Curl', 'arms', 'barbell', true),
('Dumbbell Curl', 'arms', 'dumbbell', true),
('Hammer Curl', 'arms', 'dumbbell', true),
('Incline Dumbbell Curl', 'arms', 'dumbbell', true),
('Preacher Curl', 'arms', 'barbell', true),
('Cable Curl', 'arms', 'cable', true),
('Concentration Curl', 'arms', 'dumbbell', true),
('Tricep Pushdown', 'arms', 'cable', true),
('Rope Pushdown', 'arms', 'cable', true),
('Skull Crusher', 'arms', 'barbell', true),
('Overhead Tricep Extension', 'arms', 'dumbbell', true),
('Close Grip Bench Press', 'arms', 'barbell', true),
('Tricep Dips', 'arms', 'bodyweight', true),
('Cable Overhead Extension', 'arms', 'cable', true),
('Plank', 'core', 'bodyweight', true),
('Side Plank', 'core', 'bodyweight', true),
('Crunch', 'core', 'bodyweight', true),
('Cable Crunch', 'core', 'cable', true),
('Hanging Leg Raise', 'core', 'bodyweight', true),
('Ab Wheel Rollout', 'core', 'other', true),
('Russian Twist', 'core', 'bodyweight', true),
('Dead Bug', 'core', 'bodyweight', true),
('Bird Dog', 'core', 'bodyweight', true),
('Pallof Press', 'core', 'cable', true),
('Clean and Press', 'full_body', 'barbell', true),
('Kettlebell Swing', 'full_body', 'kettlebell', true),
('Turkish Get-Up', 'full_body', 'kettlebell', true),
('Burpee', 'full_body', 'bodyweight', true),
('Thruster', 'full_body', 'barbell', true),
('Farmer''s Walk', 'full_body', 'dumbbell', true),
('Battle Ropes', 'full_body', 'other', true),
('Box Jump', 'full_body', 'bodyweight', true),
('Sled Push', 'full_body', 'other', true),
('Smith Machine Squat', 'legs', 'machine', true),
('Trap Bar Deadlift', 'back', 'barbell', true),
('Barbell Shrug', 'back', 'barbell', true),
('Dumbbell Shrug', 'back', 'dumbbell', true),
('Dumbbell Pullover', 'chest', 'dumbbell', true),
('Cable Pullover', 'back', 'cable', true),
('High Bar Squat', 'legs', 'barbell', true),
('Low Bar Squat', 'legs', 'barbell', true),
('Stiff Leg Deadlift', 'back', 'barbell', true),
('Snatch Grip Deadlift', 'back', 'barbell', true),
('Z Press', 'shoulders', 'barbell', true),
('Seated Overhead Press', 'shoulders', 'barbell', true),
('Seated Dumbbell Press', 'shoulders', 'dumbbell', true),
('Machine Lateral Raise', 'shoulders', 'machine', true),
('Cable Rear Delt Fly', 'shoulders', 'cable', true),
('Reverse Curl', 'arms', 'barbell', true),
('Drag Curl', 'arms', 'barbell', true),
('Kickback', 'arms', 'dumbbell', true),
('V-Bar Pushdown', 'arms', 'cable', true),
('Weighted Pull-Up', 'back', 'bodyweight', true),
('Weighted Chin-Up', 'back', 'bodyweight', true),
('Assisted Pull-Up', 'back', 'machine', true),
('Assisted Dip', 'arms', 'machine', true),
('Machine Pullover', 'back', 'machine', true),
('Decline Bench Press', 'chest', 'barbell', true),
('Decline Dumbbell Press', 'chest', 'dumbbell', true),
('Machine Fly', 'chest', 'machine', true),
('Single Arm Row', 'back', 'dumbbell', true),
('Single Arm Pulldown', 'back', 'cable', true),
('Single Arm Press', 'shoulders', 'dumbbell', true),
('Tempo Squat', 'legs', 'barbell', true),
('Box Squat', 'legs', 'barbell', true),
('Pause Squat', 'legs', 'barbell', true),
('Belt Squat', 'legs', 'machine', true),
('Split Squat', 'legs', 'dumbbell', true),
('Single Leg RDL', 'legs', 'dumbbell', true),
('Nordic Ham Curl', 'legs', 'bodyweight', true),
('Hollow Body Hold', 'core', 'bodyweight', true),
('Mountain Climber', 'core', 'bodyweight', true),
('V-Up', 'core', 'bodyweight', true),
('Toes to Bar', 'core', 'bodyweight', true),
('Power Clean', 'full_body', 'barbell', true),
('Hang Clean', 'full_body', 'barbell', true),
('Snatch', 'full_body', 'barbell', true),
('Muscle-Up', 'full_body', 'bodyweight', true),
('Rowing Machine', 'full_body', 'machine', true),
('Assault Bike', 'full_body', 'machine', true),
('Jump Rope', 'full_body', 'other', true),
('Resistance Band Pull Apart', 'back', 'other', true),
('Band Face Pull', 'shoulders', 'other', true),
('Band Squat', 'legs', 'other', true),
('Iso-Lateral Row', 'back', 'machine', true),
('Iso-Lateral Chest Press', 'chest', 'machine', true),
('Iso-Lateral Shoulder Press', 'shoulders', 'machine', true),
('Iso-Lateral Leg Press', 'legs', 'machine', true),
('Cable Kickback', 'legs', 'cable', true),
('Reverse Hyper', 'legs', 'machine', true),
('45 Degree Back Extension', 'back', 'bodyweight', true),
('GHD Back Extension', 'back', 'machine', true),
('GHD Sit-Up', 'core', 'machine', true),
('Pike Push-Up', 'shoulders', 'bodyweight', true),
('Handstand Push-Up', 'shoulders', 'bodyweight', true),
('Ring Row', 'back', 'bodyweight', true),
('TRX Row', 'back', 'other', true),
('TRX Push-Up', 'chest', 'other', true),
('TRX Pike', 'core', 'other', true),
('TRX Squat', 'legs', 'other', true),
('TRX Hamstring Curl', 'legs', 'other', true),
('Suitcase Carry', 'core', 'dumbbell', true),
('Overhead Carry', 'core', 'dumbbell', true),
('Front Rack Carry', 'core', 'barbell', true),
('Waiter''s Walk', 'full_body', 'dumbbell', true),
('Scaption', 'shoulders', 'dumbbell', true),
('External Rotation', 'shoulders', 'cable', true),
('Superman', 'back', 'bodyweight', true),
('Scapular Pull-Up', 'back', 'bodyweight', true),
('Archer Push-Up', 'chest', 'bodyweight', true),
('Decline Push-Up', 'chest', 'bodyweight', true),
('Incline Push-Up', 'chest', 'bodyweight', true),
('Diamond Push-Up', 'arms', 'bodyweight', true),
('Bayesian Curl', 'arms', 'cable', true),
('Spider Curl', 'arms', 'dumbbell', true),
('JM Press', 'arms', 'barbell', true),
('21s Curl', 'arms', 'barbell', true),
('Cable Woodchop', 'core', 'cable', true),
('Copenhagen Plank', 'core', 'bodyweight', true),
('L-Sit', 'core', 'bodyweight', true),
('Windmill', 'full_body', 'kettlebell', true),
('Wall Ball', 'full_body', 'other', true),
('Medicine Ball Slam', 'full_body', 'other', true),
('Ski Erg', 'full_body', 'machine', true),
('Stair Climber', 'full_body', 'machine', true),
('Treadmill Run', 'full_body', 'machine', true),
('Meadows Row', 'back', 'barbell', true),
('Seal Row', 'back', 'barbell', true),
('Yates Row', 'back', 'barbell', true),
('Kroc Row', 'back', 'dumbbell', true),
('Renegade Row', 'back', 'dumbbell', true),
('Good Morning', 'back', 'barbell', true),
('Hyperextension', 'back', 'bodyweight', true),
('Neutral Grip Pulldown', 'back', 'cable', true),
('Single Arm Cable Row', 'back', 'cable', true),
('Reverse Grip Pulldown', 'back', 'cable', true),
('Underhand Barbell Row', 'back', 'barbell', true),
('Wide Grip Barbell Row', 'back', 'barbell', true),
('Hammer Strength Row', 'back', 'machine', true),
('Hammer Strength Chest Press', 'chest', 'machine', true),
('Hammer Strength Incline Press', 'chest', 'machine', true),
('Hammer Strength Shoulder Press', 'shoulders', 'machine', true),
('Hammer Strength Lat Pulldown', 'back', 'machine', true),
('Guillotine Press', 'chest', 'barbell', true),
('Squeeze Press', 'chest', 'dumbbell', true),
('Svend Press', 'chest', 'other', true),
('Low Cable Fly', 'chest', 'cable', true),
('High Cable Fly', 'chest', 'cable', true),
('Cable Bench Press', 'chest', 'cable', true),
('Narrow Grip Bench Press', 'chest', 'barbell', true),
('Wide Grip Bench Press', 'chest', 'barbell', true),
('Paused Bench Press', 'chest', 'barbell', true),
('Spoto Press', 'chest', 'barbell', true),
('Pin Press', 'chest', 'barbell', true),
('Machine Incline Press', 'chest', 'machine', true),
('Machine Decline Press', 'chest', 'machine', true),
('Smith Machine Incline Press', 'chest', 'machine', true),
('Landmine Lateral Raise', 'shoulders', 'barbell', true),
('Push Press', 'shoulders', 'barbell', true),
('Bradford Press', 'shoulders', 'barbell', true),
('Cuban Press', 'shoulders', 'dumbbell', true),
('Y-Raise', 'shoulders', 'dumbbell', true),
('Lu Raise', 'shoulders', 'dumbbell', true),
('Leaning Lateral Raise', 'shoulders', 'dumbbell', true),
('Bent Over Lateral Raise', 'shoulders', 'dumbbell', true),
('Machine Rear Delt', 'shoulders', 'machine', true),
('Cross Cable Rear Delt', 'shoulders', 'cable', true),
('Smith Machine Overhead Press', 'shoulders', 'machine', true),
('Zottman Curl', 'arms', 'dumbbell', true),
('Cross Body Hammer Curl', 'arms', 'dumbbell', true),
('Cable Hammer Curl', 'arms', 'cable', true),
('Overhead Cable Curl', 'arms', 'cable', true),
('Tate Press', 'arms', 'dumbbell', true),
('Floor Skull Crusher', 'arms', 'barbell', true),
('Reverse Grip Pushdown', 'arms', 'cable', true),
('Bench Dip', 'arms', 'bodyweight', true),
('Ring Dip', 'arms', 'bodyweight', true),
('Wrist Curl', 'arms', 'barbell', true),
('Reverse Wrist Curl', 'arms', 'barbell', true),
('Pistol Squat', 'legs', 'bodyweight', true),
('Sissy Squat', 'legs', 'bodyweight', true),
('Nordic Curl', 'legs', 'bodyweight', true),
('Zercher Squat', 'legs', 'barbell', true),
('Jefferson Squat', 'legs', 'barbell', true),
('Cable Pull Through', 'legs', 'cable', true),
('Glute Ham Raise', 'legs', 'machine', true),
('Donkey Calf Raise', 'legs', 'machine', true),
('Adductor Machine', 'legs', 'machine', true),
('Abductor Machine', 'legs', 'machine', true),
('Hip Abduction Machine', 'legs', 'machine', true),
('Hip Adduction Machine', 'legs', 'machine', true),
('Frog Pump', 'legs', 'bodyweight', true),
('Curtsy Lunge', 'legs', 'dumbbell', true),
('Pendulum Squat', 'legs', 'machine', true),
('Safety Bar Squat', 'legs', 'barbell', true),
('Deficit Deadlift', 'back', 'barbell', true),
('Block Pull', 'back', 'barbell', true),
('Paused Deadlift', 'back', 'barbell', true),
('Single Leg Deadlift', 'legs', 'dumbbell', true),
('Cable Shrug', 'back', 'cable', true),
('Smith Machine Row', 'back', 'machine', true),
('Smith Machine Shrug', 'back', 'machine', true),
('Chest Supported T-Bar Row', 'back', 'machine', true),
('Machine Crunch', 'core', 'machine', true),
('Decline Sit-Up', 'core', 'bodyweight', true),
('Cable Woodchop Low to High', 'core', 'cable', true),
('Dragon Flag', 'core', 'bodyweight', true),
('Band Pallof Press', 'core', 'other', true),
('Band Chest Press', 'chest', 'other', true),
('Band Row', 'back', 'other', true),
('Band Curl', 'arms', 'other', true),
('Band Tricep Extension', 'arms', 'other', true),
('Band Lateral Walk', 'legs', 'other', true),
('Band Good Morning', 'back', 'other', true),
('Elliptical', 'full_body', 'machine', true),
('Tire Flip', 'full_body', 'other', true),
('Sandbag Clean', 'full_body', 'other', true),
('Sandbag Carry', 'full_body', 'other', true),
('Log Press', 'full_body', 'other', true),
('Zercher Carry', 'full_body', 'barbell', true),
('Cross Carry', 'full_body', 'dumbbell', true),
('Pinwheel Curl', 'arms', 'dumbbell', true),
('Incline Skull Crusher', 'arms', 'barbell', true),
('Decline Skull Crusher', 'arms', 'barbell', true),
('Cable Kickback Tricep', 'arms', 'cable', true),
('Straight Bar Pushdown', 'arms', 'cable', true),
('Rope Hammer Curl', 'arms', 'cable', true),
('Fat Grip Curl', 'arms', 'barbell', true),
('Fat Grip Row', 'back', 'barbell', true),
('Fat Grip Bench', 'chest', 'barbell', true),
('Single Arm Dumbbell Press', 'chest', 'dumbbell', true),
('Single Arm Cable Press', 'chest', 'cable', true),
('Single Arm Lateral Raise', 'shoulders', 'dumbbell', true),
('Single Arm Tricep Extension', 'arms', 'dumbbell', true),
('Single Arm Curl', 'arms', 'dumbbell', true),
('Single Leg Press', 'legs', 'machine', true),
('Single Leg Extension', 'legs', 'machine', true),
('Single Leg Curl', 'legs', 'machine', true),
('Cable Glute Kickback', 'legs', 'cable', true),
('Fire Hydrant', 'legs', 'bodyweight', true),
('Clamshell', 'legs', 'bodyweight', true),
('Anderson Squat', 'legs', 'barbell', true),
('Competition Squat', 'legs', 'barbell', true),
('Pin Squat', 'legs', 'barbell', true),
('Jefferson Deadlift', 'back', 'barbell', true),
('Jefferson Bench Press', 'chest', 'barbell', true),
('Landmine Press Shoulder', 'shoulders', 'barbell', true),
('Standing Cable Press', 'shoulders', 'cable', true),
('Cable Front Raise', 'shoulders', 'cable', true),
('Prone Y Raise', 'shoulders', 'dumbbell', true),
('Prone T Raise', 'shoulders', 'dumbbell', true),
('Full Can Raise', 'shoulders', 'dumbbell', true),
('Internal Rotation', 'shoulders', 'cable', true),
('Band External Rotation', 'shoulders', 'other', true),
('Band Internal Rotation', 'shoulders', 'other', true),
('Scapular Push-Up', 'chest', 'bodyweight', true),
('Ring Push-Up', 'chest', 'bodyweight', true),
('Explosive Push-Up', 'chest', 'bodyweight', true),
('Clapping Push-Up', 'chest', 'bodyweight', true),
('Hindu Push-Up', 'chest', 'bodyweight', true),
('Pseudo Planche Push-Up', 'chest', 'bodyweight', true),
('Typewriter Pull-Up', 'back', 'bodyweight', true),
('Commando Pull-Up', 'back', 'bodyweight', true),
('L-Sit Pull-Up', 'back', 'bodyweight', true),
('TRX Fallout', 'core', 'other', true),
('TRX Mountain Climber', 'core', 'other', true),
('TRX Sprinter Start', 'legs', 'other', true),
('TRX Lunge', 'legs', 'other', true),
('TRX Y Fly', 'shoulders', 'other', true),
('TRX Bicep Curl', 'arms', 'other', true),
('TRX Tricep Extension', 'arms', 'other', true),
('Rack Pull Shrug', 'back', 'barbell', true),
('Behind Back Shrug', 'back', 'barbell', true),
('Trap Bar Shrug', 'back', 'barbell', true),
('Machine Dip', 'arms', 'machine', true),
('Weighted Dip', 'arms', 'bodyweight', true),
('Barbell Pullover', 'chest', 'barbell', true),
('Board Press', 'chest', 'barbell', true),
('Reverse Band Bench', 'chest', 'barbell', true),
('Chain Bench Press', 'chest', 'barbell', true),
('Banded Deadlift', 'back', 'barbell', true),
('Chain Deadlift', 'back', 'barbell', true),
('Wrist Roller', 'arms', 'other', true),
('Wall Handstand Hold', 'shoulders', 'bodyweight', true),
('Cat Cow', 'core', 'bodyweight', true),
('Reverse Hyperextension', 'back', 'bodyweight', true),
('Dive Bomber Push-Up', 'chest', 'bodyweight', true),
('Wide Push-Up', 'chest', 'bodyweight', true),
('Close Grip Push-Up', 'arms', 'bodyweight', true),
('Empty Can Raise', 'shoulders', 'dumbbell', true),
('Prone W Raise', 'shoulders', 'dumbbell', true),
('Scarecrow', 'shoulders', 'dumbbell', true),
('Behind Neck Press', 'shoulders', 'barbell', true),
('Decline Dumbbell Fly', 'chest', 'dumbbell', true),
('Machine Incline Press Alt', 'chest', 'machine', true)
on conflict do nothing;
